### ISSUE TITLE
Failure to build with older glibc

### ISSUE THREAD

**Issue by danilaml** [KhronosGroup/Vulkan-LoaderAndValidationLayers#204]
```
/Vulkan/Vulkan-LoaderAndValidationLayers/loader/libvulkan.so.1.0.5: undefined reference to `secure_getenv'
```
I think this change: https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/commit/a867ee49907c70fcc8135547e17c14f034eccb3d#diff-5b4e070f5ce5cbb7bd1dd11f689d50a8R2278
introduced this problem. It fails to build on older OSes like Ubuntu 12.04 (crucial for travis build bots).

I think that workaround [suggested here](https://sourceware.org/glibc/wiki/Tips_and_Tricks/secure_getenv) should fix this issue but I haven't tried it yet.

**Comment by jon-lunarg** [comment]
Pushed a fix to master branch:

commit 7f7fea8ef08f8b9e24ca9151154e8dd945c5bf3e
Author: Jon Ashburn <jon@lunarg.com>
Date:   Mon Apr 4 13:52:53 2016 -0600

    loader: ghlvl #204, Use __secure_getenv if secure_getenv is unavailable
    
    Also add group id check to getenv suid check in loader.
    
    Change-Id: Icbc08258498f893ee5fce144c043bdc6bd8e5423


I wasn't able to test this on older versions of glibc, reopen an issue if it doesn't work.

**Comment by Delwin9999** [comment]
It does not work on glibc 2.12

../loader/libvulkan.so.1.0.8: undefined reference to `secure_getenv'

**Comment by jon-lunarg** [comment]
Did you build a new loader or use the one built and distributed in in SDK-1.0.8.  The fix is a compile time thing, so the loader built and distributed with SDK-1.0.8 would still have the issue.

**Comment by Delwin9999** [comment]
that was a newly built loader on CentOS 6.8 with GCC 4.9

**Comment by jon-lunarg** [comment]
There is a problem with the existing fix; reopening this issue.

**Comment by jon-lunarg** [comment]
Hi Delwin:
I pushed a new fix to master branch. Can you test if this fixes the issue?

**Comment by Delwin9999** [comment]
I can test this tomorrow.  Sorry my schedule is a little wacky right now.

**Comment by jon-lunarg** [comment]
Closing this issue since I think it is fixed now.  reopen if necessary.
